# Conversation states
(IDENTIFY, PHONE, OFFER, REJECT_REASON, ADMIN_ADD_CODE, 
 ADMIN_ADD_CREDITS, ADMIN_DELETE_CONFIRM, ADMIN_SELECT_USER_FOR_CREDIT, 
 ADMIN_ALTER_CREDIT, REFILL_STATE, TX_VERIFICATION_STATE) = range(11)

# Other constants
USDT_WALLET = "TBDchgvJed9ghdUsQrZxf6UgGmZR95eaT1"
ADMIN_ID = 7168043490
BOT_TOKEN = "7739976856:AAHwabJ3g73GGccW4oy72cP8JRmAoodfLTs"