# Conversation states
(IDENTIFY, PHONE, OFFER, REJECT_REASON, ADMIN_ADD_CODE, 
 ADMIN_ADD_CREDITS, ADMIN_DELETE_CONFIRM, ADMIN_SELECT_USER_FOR_CREDIT, 
 ADMIN_ALTER_CREDIT, REFILL_STATE, TX_VERIFICATION_STATE) = range(11)

# Other constants
USDT_WALLET = "TRx5hG9tK7LzabT8vMy5oH2jzEpYFC6iVU"
ADMIN_ID = 5819282818
BOT_TOKEN = "7739976856:AAHwabJ3g73GGccW4oy72cP8JRmAoodfLTs"